namespace Offset{
enum Offsets {
 
//*NO NEED TO OPEN THAT BULLSHIT AGAIN AND AGAIN
getposition = 0xC1E548, //CLASS TRANSFORM -> GET_POSITION_INJECTED
Camera = 0x109661C, //CLASS CAMERA -> CAMERA GET_MAIN OR OTHER
gettransform = 0x1097EB0, //CLASS COMPONENT -> GET_TRANSFORM
WorldToScreenPoint = 0x1095FE8, //CLASS CAMERA -> WORLDTOSCREENPOINT_INJECTED


};
}

